// frontend/src/lib/api/endpoints.ts

export const API_ENDPOINTS = {
  identity: {
    register: '/api/v1/identity/register',
    login: '/api/v1/identity/login',
    me: '/api/v1/identity/me',
    changePassword: '/api/v1/identity/password/change',
    revokeToken: '/api/v1/identity/revoke-token',
    certificationSubmit: '/api/v1/identity/certification/submit',
    updateCampusStatus: '/api/v1/identity/campus-status',
  },
  schools: {
    publicList: '/api/v1/schools/public',
  },
  enrollment: {
    claim: '/api/v1/enrollment/claim',
    activate: '/api/v1/enrollment/activate',
    status: '/api/v1/enrollment/status',
  },
  ads: {
    feed: '/api/v1/ads/feed',
    impression: '/api/v1/ads/impression',
    click: (token: string) => `/api/v1/ads/click/${token}`,
    feedback: '/api/v1/ads/feedback',
  },
  advertiser: {
    register: '/api/v1/advertiser/register',
    me: '/api/v1/advertiser/me',
    walletTopup: '/api/v1/advertiser/wallet/topup',
    campaigns: '/api/v1/advertiser/campaigns',
    submitCreative: (campaignId: string) => `/api/v1/advertiser/campaigns/${campaignId}/creatives`,
    campaignStats: (campaignId: string) => `/api/v1/advertiser/campaigns/${campaignId}/stats`,
  },
  feed: {
    posts: '/api/v1/community/feed',
  },
  community: {
    feed: '/api/v1/community/feed',
    rooms: '/api/v1/community/rooms',
    declareRoom: (roomId: string) => `/api/v1/community/rooms/${roomId}/status`,
    declareRoomStatus: (roomId: string) => `/api/v1/community/rooms/${roomId}/status`,
    flagRoom: (roomId: string) => `/api/v1/community/rooms/${roomId}/flag`,
    organizations: '/api/v1/community/organizations',
    posts: '/api/v1/community/posts',
    classAnnouncements: (classId: string) => `/api/v1/classes/${classId}/announcements`,
    classIncidents: (classId: string) => `/api/v1/classes/${classId}/incidents`,
    classPolls: (classId: string) => `/api/v1/classes/${classId}/polls`,
    classEvents: (classId: string) => `/api/v1/classes/${classId}/events`,
  },
  classDelegate: {
    announcements: (classId: string) => `/api/v1/classes/${classId}/announcements`,
    incidents: (classId: string) => `/api/v1/classes/${classId}/incidents`,
    polls: (classId: string) => `/api/v1/classes/${classId}/polls`,
    votePoll: (classId: string, pollId: string) => `/api/v1/classes/${classId}/polls/${pollId}/vote`,
    closePoll: (classId: string, pollId: string) => `/api/v1/classes/${classId}/polls/${pollId}/close`,
    events: (classId: string) => `/api/v1/classes/${classId}/events`,
  },
  admin: {
    dashboard: '/api/v1/admin/dashboard',
    roster: '/api/v1/admin/roster',
    rosterImport: '/api/v1/admin/roster/import',
    invitations: '/api/v1/admin/invitations',
    bulkInvitations: '/api/v1/admin/invitations/bulk',
    memberships: '/api/v1/admin/memberships',
    approveMembership: (id: string) => `/api/v1/admin/memberships/${id}/approve`,
    rejectMembership: (id: string) => `/api/v1/admin/memberships/${id}/reject`,
    resendInvitation: (id: string) => `/api/v1/admin/invitations/${id}/resend`,
    revokeInvitation: (id: string) => `/api/v1/admin/invitations/${id}/revoke`,
    classes: '/api/v1/admin/classes',
    rooms: '/api/v1/admin/rooms',
    classDelegates: (classId: string) => `/api/v1/admin/classes/${classId}/delegates`,
    settings: '/api/v1/admin/settings',
    subscription: '/api/v1/admin/subscription',
    audit: '/api/v1/admin/audit',
    monetization: '/api/v1/admin/monetization',
  },
  monetization: {
    licenseStatus: '/api/v1/admin/monetization/license',
  },
  platform: {
    tenants: '/api/v1/platform/tenants',
    updateSubscription: (tenantId: string) => `/api/v1/platform/tenants/${tenantId}/subscription`,
  },
  democracy: {
    elections: '/api/v1/democracy/elections',
    vote: (electionId: string) => `/api/v1/democracy/elections/${electionId}/vote`,
    tally: (electionId: string) => `/api/v1/democracy/elections/${electionId}/tally`,
  },
  academy: {
    library: '/api/v1/academy/library',
    upload: '/api/v1/academy/library/upload',
    purchase: '/api/v1/academy/library/purchase',
    readerStream: (docId: string) => `/api/v1/academy/library/stream/${docId}`,
  },
  campusLife: {
    marketplace: '/api/v1/campus-life/marketplace',
    rides: '/api/v1/campus-life/ride',
    bookRide: (rideId?: string) => `/api/v1/campus-life/ride/${rideId || ''}/book`,
    messages: (conversationId: string) => `/api/v1/messages/${conversationId}`,
    sendMessage: '/api/v1/messages/send',
  },
  opportunities: {
    list: '/api/v1/opportunities',
    apply: (id: string) => `/api/v1/opportunities/${id}/apply`,
    create: '/api/v1/opportunities',
  },
  messaging: {
    messages: (conversationId: string) => `/api/v1/messages/${conversationId}`,
    sendMessage: '/api/v1/messages/send',
  },
  notifications: {
    list: '/api/v1/notifications',
    unreadCount: '/api/v1/notifications/unread-count',
    markRead: (id: string) => `/api/v1/notifications/${id}/read`,
    markAllRead: '/api/v1/notifications/read-all',
    preferences: '/api/v1/notifications/preferences',
    quietHours: '/api/v1/notifications/quiet-hours',
    pushSubscribe: '/api/v1/notifications/push/subscribe',
    pushUnsubscribe: '/api/v1/notifications/push/unsubscribe',
    broadcast: '/api/v1/notifications/broadcast',
    analytics: '/api/v1/notifications/admin/analytics',
  },
};

export const endpoints = API_ENDPOINTS;
export default API_ENDPOINTS;