name: Deploy Pipeline

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy status
        run: echo "Ready for deployment."
